# Generated by Django 5.1.7 on 2025-03-27 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_mailing_finish_send_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="finish_send_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 28, 13, 10, 28, 581634),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_send_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 27, 13, 10, 28, 581634),
                verbose_name="Дата и время первой отправки",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(
                help_text="Адрес почты должен быть уникальным",
                max_length=254,
                verbose_name="Почта",
            ),
        ),
    ]
