version: '3.12'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Порт для доступа к бэкенду
    env_file:
      - .env
    volumes:
      - .:/app  # Монтирование текущей директории в контейнер
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
